### ISSUE TITLE
Split docker host config for remote and local hosts

### ISSUE THREAD

**Issue by pythoninthegrass** [pulumi/pulumi-docker#1266]
This is more of a question. Looking through the [docs](https://www.pulumi.com/registry/packages/docker/#configuration-reference), I'm not sure if it's possible to split the docker host ([DOCKER_HOST](https://www.pulumi.com/registry/packages/docker/installation-configuration/#configuring-the-provider)) configuration in `Pulumi.yml`:
```yaml
name: pulumi_docker
runtime:
  name: python
  options:
    toolchain: poetry
    virtualenv: .venv
    typechecker: mypy
description: Use the docker provider to setup local and remote containers
config:
  docker:host:
    value: unix:///var/run/docker.sock
  docker:host:
    value: ssh://user@remote-host:22
  docker:sshOpts:
    value:
        - -o
        - StrictHostKeyChecking=no
        - -o
        - UserKnownHostsFile=/dev/null
  pulumi:tags:
    value:
      pulumi:template: https://www.pulumi.com/ai/api/project/52d80566-92ad-49af-8b0c-0e5eb4f3d53e.zip
```
This of course fails as it's a duplicate key
```
λ pulumi config
error: could not unmarshal '/Users/lance.stephens/git/pulumi_docker/Pulumi.yml': yaml: unmarshal errors:
  line 12: mapping key "docker:host" already defined at line 10
```

My use case is that I want _some_ containers to be local while others are remote (or both). An example of this workflow is that on the pulumi host (controller?), it needs prometheus, grafana, and the node-exporter for linux. But on remote nodes, certain prometheus exporters will be deployed (e.g., mongo, redis, elasticsearch, etc.)

The business logic can easily handle this, but not sure how pulumi abstracts the underlying terraform and if that's possible without writing separate stacks.
