### ISSUE TITLE
Consider default platform selections, windows/amd64 may not be the best default on Windows

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-docker#534]
The Image v4 resource defaults to, `platform: "windows/amd64"` on Windows assuming #535 is fixed, resulting in errors when building. The default platform behavior of the Docker daemon seems correct when `platform: ""` (the empty string).

The default behavior here may be the correct one, though we ought to investigate what macOS platforms perform here and what default is best there.

Given the same program as in #535:

```yaml
name: image-yaml
description: A Docker image build
runtime: yaml
config: {}
variables: {}
resources:
  demo-image:
    type: docker:Image
    properties:
      imageName: username/image:tag1
      skipPush: true
      build:
        context: ./app
        platform: windows/amd64 # assuming this became the new default
    options:
      version: v4.0.0
outputs:
  imageName: ${demo-image.imageName}
```

With this Dockerfile:

```Dockerfile
FROM busybox:latest

COPY test.txt /

CMD ["cat", "test.txt"]
```

Results in this error:

```
error: failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:c118f538365369207c12e5794c3cbfb7b042d950af590ae6c287ede74f29b7d4: not found
error: update failed
```
