### ISSUE TITLE
Building on Windows without platform set results in error

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-docker#535]
When building an image like so on Windows:

```yaml
name: image-yaml
description: A Docker image build
runtime: yaml
config: {}
variables: {}
resources:
  demo-image:
    type: docker:Image
    properties:
      imageName: username/image:tag1
      skipPush: true
      build:
        context: ./app
    options:
      version: v4.0.0
outputs:
  imageName: ${demo-image.imageName}
```

With this Dockerfile:

```
FROM busybox:latest

COPY test.txt /

CMD ["cat", "test.txt"]
```

The program fails with:

```
error: failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:c118f538365369207c12e5794c3cbfb7b042d950af590ae6c287ede74f29b7d4: not found
```

This sha is the digest of `busybox:latest`; it appears we are trying to select "windows/amd64" as the platform. See #534 for further consideration.
