### ISSUE TITLE
docker:index:Image could not open dockerfile at relative path Dockerfile when using pulumi/actions@v4

### ISSUE THREAD

**Issue by dkezri** [pulumi/pulumi-docker#844]
I have two docker files each in different directories inside my Pulumi .net project for Azure. 
Everything works fine when i run "pulumi up"  locally on my windows PC. but when i use github actions to deploy it, i get this error: 

 "**docker:index:Image could not open dockerfile at relative path Dockerfile**".  

i have created a method that accepst the template directory which contains the  Dockerfile.
```
public Image CreateDockerImage( RegistryHelper registry, string name, string dockerFileDir)
            var image = new Docker.Image(name, new()
            {
                ImageName = name,
                Build = new Docker.Inputs.DockerBuildArgs
                {
                    Context = $"./Templates/{dockerFileDir}",
                    Platform = "linux/amd64"         
                },
                Registry = new Docker.Inputs.RegistryArgs
                {
                    Server = registry.LoginServer,
                    Username =registry.adminUserName,
                    Password = registry.adminPassword,
                },
            }

```
**Here is the github actions step to run "pulumi up"**

```
      - name: pulumi preview step
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          cloud-url: azblob://${{ env.AZURE_CONTAINER_NAME }}
          work-dir:  ./PulumiAzure
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID_DEV }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID_DEV }}
          AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ env.AZURE_STORAGE_KEY }}
          AZURE_KEYVAULT_AUTH_VIA_CLI: true

           
```
Here is my application structure i .Net c# :

- **PulumiAzureRootDir**
    - **PulumiAzure**
        - Modules
        - Templates
           - ContainerApps
              - Dockerfile
              - entrypoint.sh
            - Webapps
               - Dockerfile
               - entrypoint.sh
        - MainStack.cs
        - Program.cs
        - pulumi.dev.yaml
        - pulumi.yaml
   - **PulumiAzureTest**
        - Core
        - ContainerAppTests.cs
